        					</div>
			    	    </article>
                	<div class="clearfix">
            		</div>
        			</div>
			    	<div class="col-md-3 col-md-offset-1 sidebar">
						<aside id="nav_menu-2" class="widget widget_nav_menu">
							<h3 class="widget-title">Navigation</h3>
							<div class="menu-right-nav-container">
								<ul id="menu-right-nav" class="menu">
									<li id="menu-item-22" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-22 special-class"><a href="/about/">About</a></li>
									<li id="menu-item-42" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-42 special-class"><a href="/what-is-bullying/">What is bullying</a></li>
									<li id="menu-item-46" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-46 special-class"><a href="/fighting-bullying/">Fighting bullying</a></li>
									<li id="menu-item-48" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-48 special-class"><a href="/live-chat/">Live Chat</a></li>
									<li id="menu-item-53" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-53 special-class"><a href="/contact/">Contact</a></li>
								</ul>
							</div>
						</aside>
						<aside id="nav_menu-3" class="widget widget_nav_menu">
							<h3 class="widget-title">Fighting Bullying</h3>
							<div class="menu-fighting-bullying-container">
								<ul id="menu-fighting-bullying" class="menu">
									<li id="menu-item-79" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-79 special-class"><a href="/fighting-bullying/helpful-tips/">Helpful Tips</a></li>
									<li id="menu-item-80" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-80 special-class"><a href="/fighting-bullying/anti-bully-alias/">Anti-Bully-Alias</a></li>
									<li id="menu-item-81" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-81 special-class"><a href="/fighting-bullying/best-practice/">Best Practice</a></li>
								</ul>
							</div>
						</aside>
				    </div>
			    </div>
			</div>  
		</div>
		<footer class="footer">
			<div class="container">
				<div class="row">
					<aside id="text-2" class="col-md-3 footer-separator widget_text">
						<h6>Instant help</h6>
						<div class="textwidget"> 
							<a href="/best-practice">Read our Best Practice page</a>
						</div>
					</aside>
					<aside id="text-3" class="col-md-3 footer-separator widget_text">
						<h6>Anti-Bully-Alias</h6>
						<div class="textwidget"> 
							<a href="/fighting-bullying/anti-bully-alias">Get our proven Anti-Bully-Alias</a>
						</div>
					</aside>
					<aside id="text-4" class="col-md-3 footer-separator widget_text">
						<h6>Helpful Tips</h6>
						<div class="textwidget">
							<a href="/helpful-tips">Read important tips</a>
						</div>
					</aside>      
					<aside class="col-md-3 footer-separator" id="follow_us">
						<h6>Follow Us</h6>
						<ul class=" list-unstyled social">
							<li><a href="https://plus.google.com/+StopircbullyingEurope" target="_blank" class="sprite facebook-icon">facebook</a></li>
							<li><a href="https://twitter.com/StopIRCbullying" target="_blank" class="sprite twitter-icon">twitter</a></li>
						</ul>
						<div class="copyright">
							<span><br />						           © 2013-2019, Stop IRC Bullying Foundation          </span> 
						</div>
					</aside>
				</div>
			</div>
		</footer>
	</body>
</html>