<html>
	<head>
		<title>Stop IRC Bullying!</title>
		<link rel="stylesheet" type="text/css" href="/files/style.css" />
		<link rel="stylesheet" type="text/css" href="/files/bootstrap.css" />
		<link rel="icon" type="image/png" href="/files/favicon.png" />
	</head>
	<body class="home blog">
		<header class="header">
			<div class="navbar navbar-inverse" role="navigation">
		    	<div class="container">
		            <div class="navbar-header">
		        		<a class="navbar-brand head_title" href="/">        Stop bullying on IRC!        </a> 
		        	</div>
		    		<div class="menu-top-links-container">
		    			<ul id="menu" class="navbar-right menu-ommune">
		    				<li id="menu-item-51" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-51 special-class"><a href="/about/">About</a></li>
							<li id="menu-item-56" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-56 special-class"><a href="/what-is-bullying/">What is bullying</a></li>
							<li id="menu-item-55" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-55 special-class"><a href="/fighting-bullying/">Fighting bullying</a></li>
							<li id="menu-item-50" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-50 special-class"><a href="/live-chat/">Live Chat</a></li>
						</ul>
					</div>
				</div>
			</div> 
		</header>

		<div class="main-container">
  			<div class="container"> 
			    <div class="row">
    				<div class="col-md-8 main">
                		<article class="post">
                    		<div class="post-content">