<h2>About the Stop IRC Bullying Foundation</h2>
<p>The Stop IRC Bullying Foundation is a foundation based in Sweden, which aims to help any people bullied on Internet Relay Chat.</p>
<p>We are against bullying and harassment on IRC and want that everyone on IRC is treated nicely.<br>
<a title="What is bullying" href="https://web.archive.org/web/20171013024907/http://stop-irc-bullying.eu/what-is-bullying"><strong>Bullying on IRC</strong></a>&nbsp;is a&nbsp;<strong>very serious issue</strong>&nbsp;and should be seen as that – it just does not belong there.</p>
<p>The foundation is funded by anonymous donors, of which some of them were IRC-bully-victims.</p>
<p>Together we are strong and continue to fight any bullying on IRC.</p>
<p>Spread the word of our&nbsp;humanitarian organisation and help raising awareness about bullying on IRC.</p>
<p><em>—<br>
Nico Bengtsson<br>
Founder and representative of the Stop Bullying IRC Foundation<br>
</em></p>
<p>&nbsp;</p>
<p style="text-align: center;"><iframe style="display: block; margin-left: auto; margin-right: auto;" title="StopBullying Logo Widget" src="//www.stopbullying.gov/stay-connected/logo.html" marginwidth="0" marginheight="0" scrolling="no" width="194" height="50" frameborder="0"></iframe></p>