<h2>Best practice to stop being bullied on IRC</h2>
<p>If you are being bullied right now follow this steps:</p>
<ol>
<li><strong>Tell</strong>&nbsp;the person bullying you&nbsp;<strong>to stop</strong>&nbsp;it in a friendly way (eg. “Bully: please stop with this, I don’t want this”) – Also see&nbsp;<a title="Anti-Bully-Alias" href="/anti-bully-alias">Anti-Bully-Alias</a>&nbsp;for half-automating this</li>
<li>If the bully is not respecting this and continues,&nbsp;<strong>ask</strong>&nbsp;a&nbsp;<strong>channel operator</strong>&nbsp;(the people with the !, ~, &amp;,&nbsp;<strong>@</strong>, % signs infront of their nicknames) to&nbsp;<strong>kick</strong>&nbsp;the offending&nbsp;<strong>bully</strong></li>
<li>If the bully re-joins the channel then again politely&nbsp;<strong>ask</strong>&nbsp;a&nbsp;<strong>channel operator</strong>&nbsp;to&nbsp;<strong>ban</strong>&nbsp;the offending <strong>bully</strong></li>
<li>If the bully continues to harass you via private messaging (also called query) then&nbsp;use&nbsp;<strong>/ignore bully </strong>(where “bully” stands for the bullies nickname)</li>
<li><strong>As a last measure, if none</strong>&nbsp;of the previous steps have&nbsp;<strong>helped,</strong>&nbsp;eg. the bully is harassing you with multiple clients (clones) or similar (often /motd shows you what is illegal to do on a IRC-server), &nbsp;<strong>join</strong>&nbsp;the networks help channel (mostly this is&nbsp;<strong>#help</strong>)&nbsp;and&nbsp;<strong>ask</strong>&nbsp;for the&nbsp;<strong>bully</strong>&nbsp;being&nbsp;<strong>removed from</strong>&nbsp;the&nbsp;<strong>network</strong>&nbsp;(technical terms for this are: akill, gline, kline) —&nbsp;Really only do this if the previous steps have failed multiple times!</li>
</ol>
<p><strong>It is important to try steps 1, 2 and 3 first before using /ignore!</strong>&nbsp;If you just /ignore the bully he will most likely continue to bully other users. Think about the other users too!</p>
<p>Remember that /quit is not an option to stop bullying!<br>
<br>
<img class="alignnone size-full wp-image-64" alt="" src="/img/5.jpg" width="600" height="435"></p>