<h2>Fighting bullying on IRC</h2>
<p>On the right you can find pages about how to prevent bullying on IRC. As of now those include&nbsp;<a title="Best Practice" href="/best-practice">Best Practice,</a>&nbsp;our&nbsp;<a title="Anti-Bully-Alias" href="/anti-bully-alias">Anti-Bully-Alias</a>&nbsp;and&nbsp;<a title="Helpful Tips" href="/helpful-tips">Helpful Tips.</a></p>
<p>If you are being bullied right now and need&nbsp;<strong>quick help</strong>&nbsp;then either&nbsp;<strong>check</strong>&nbsp;the&nbsp;<strong><a title="Best practice" href="/best-practice">Best practice</a></strong>&nbsp;page or come chat with us on our&nbsp;<a title="Live chat" href="/live-chat">Live chat.</a></p>
<p>We also have a nice<strong>&nbsp;page which you can show to</strong>&nbsp;any&nbsp;<strong>bullies</strong>&nbsp;on IRC:&nbsp;<a title="Bully-Landing-Page" href="/stop">http://stop-irc-bullying.info/stop</a></p>
<p>
<img class="alignnone size-full wp-image-44" alt="" src="/img/1.jpg" width="600" height="423"><br>
<br>
Don’t just /ignore – /kick instead! Remember that /quit is not a solution!</p>