<h3>Helpful tips on fighting bullying on IRC</h3>
<h3>Do not counter-bully</h3>
<p>Under&nbsp;<strong>no circumstances</strong>&nbsp;you should&nbsp;<strong>counter-bully</strong>&nbsp;or be mean to the person bullying you. This is very important since otherwise you will wind eachother up more and more and&nbsp;<strong>you become a bully too!</strong>&nbsp;This is not a solution!</p>
<h3>Raise IRC-Bullying awareness</h3>
<p>To help raising awareness about bullying on IRC you can put the&nbsp;<strong>following code on&nbsp;</strong>your<strong>&nbsp;website:</strong></p>
<pre>&lt;span style="background: red; border: 1px solid black;padding: 3px;font-weight: bold;"&gt;IRC-Bullying-Awareness &amp;mdash; We support the &lt;a href="http://stop-irc-bullying.info/" title="Stop bullying on IRC now!"&gt;Stop IRC Bullying Foundation!&lt;/a&gt;&lt;/span&gt;</pre>
<p><img class="alignnone size-full wp-image-71" src="/img/4.jpg" alt="4" width="500" height="333"></p>