<h2>What is bullying on IRC?</h2>
<p>You may ask yourself what bullying on Internet Relay Chat includes.</p>
<p>This is why we have summarized a list for you:</p>
<ul>
<li>rumors</li>
<li>gossiping</li>
<li>teasing</li>
<li>insults</li>
<li>threats</li>
<li>lies</li>
<li>name-calling</li>
<li>harassment</li>
<li>mean words</li>
<li>trolling</li>
</ul>
<p>Anything of the above (and probably more techniques) are considered bullying.<br>
If you need&nbsp;<strong>instant help</strong>,&nbsp;<strong>check&nbsp;<a title="Best Practice" href="/best-practice">Best Practice.</a></strong></p>
<p><strong>Bullying on IRC</strong>&nbsp;is a&nbsp;<strong>very serious problem</strong> and can&nbsp;<strong>not only depress</strong>&nbsp;people but even drive them into&nbsp;<strong>suicide!&nbsp;</strong>This is why it is&nbsp;<strong>important</strong> for you&nbsp;<strong>to take action against</strong>&nbsp;any&nbsp;<strong>bullying on IRC!</strong></p>
<p><img class="wp-image-28 alignleft" alt="" src="/img/2.jpg" width="512" height="334"></p>